<?php

namespace Esor\TestBundle\Repository;
use Doctrine\ORM\Mapping as ORM;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\QueryBuilder;

class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function whereCurrentYear(QueryBuilder $qb)
    {
        $qb
            ->andWhere('a.date BETWEEN :start AND :end')
            ->setParameter('start', new \Datetime(date('Y') . '-01-01'))// Date entre le 1er janvier de cette année
            ->setParameter('end', new \Datetime(date('Y') . '-12-31'))  // Et le 31 décembre de cette année
        ;
    }


    public function getAdvertWithApplications()
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->innerjoin('a.applications', 'app')
            ->addSelect('app');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getAdvertWithCategories(array $categoryNames)
    {

        $qb = $this->createQueryBuilder('a');
        //jointure
        $qb->innerjoin('a.categories', 'c')->addSelect('c');

        // Puis on filtre sur le nom des catégories à l'aide d'un IN
        $qb->where($qb->expr()->in('c.name', $categoryNames));
        // La syntaxe du IN et d'autres expressions se trouve dans la documentation Doctrine

        // Enfin, on retourne le résultat
        return $qb
            ->getQuery()
            ->getResult();


    }
}
